Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;
using NuGet.Packaging.Signing;

namespace MyModel_CodeFirst.Controllers
{
    public class BooksController : Controller
    {
        private readonly GuestBookContext _context;

        public BooksController(GuestBookContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            // 依照 TimeStamp 由新到舊排序
            return View(await _context.Book.OrderByDescending(b => b.TimeStamp).ThenByDescending(b => b.GId).ToListAsync());
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FirstOrDefaultAsync(m => m.GId == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("GId,Title,Description,Author,TimeStamp,Photo,ImageType")] Book book)
        {
            if (id != book.GId)
            {
                return NotFound();
            }

            book.TimeStamp = DateTime.Now;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.GId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Books/DeleteReBook/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReBook(long id)
        {
            var reBook = await _context.ReBook.FindAsync(id);

            if (reBook != null)
            {
                _context.ReBook.Remove(reBook);
                await _context.SaveChangesAsync();
                return RedirectToAction("Delete", new { id = reBook.GId });
            }

            return NotFound();
        }

        // Check if a book exists
        private bool BookExists(long id)
        {
            return _context.Book.Any(e => e.GId == id);
        }

        // GET: Books/GetImage/5
        public async Task<FileContentResult> GetImage(long gid)
        {
            var book = await _context.Book.FindAsync(gid);

            if (book == null || book.Photo == null)
            {
                // Return a default image if the book or photo is not found
                return File(new byte[0], "image/jpeg"); // You might want to return a default image here
            }

            return File(book.Photo, book.ImageType);
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;
using Newtonsoft.Json;

namespace MyModel_CodeFirst.Controllers
{
    public class LoginController : Controller
    {
        private readonly GuestBookContext _context;

        public LoginController(GuestBookContext context)
        {
            _context = context;
        }

        //4.2.4 建立Get與Post的Login Action
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Login login)
        {

            //如果帳密正確,導入後台頁面

            //如果帳密不正確,回到登入頁面,並告知帳密錯誤

            //如果帳密正確
            //  導入後台頁面
            //否則
            // 回到登入頁面,並告知帳密錯誤

            if (login == null)
            {
                return View();
            }


            //select * from Login where account=@account and password=@password

            var result = await _context.Login.Where(m => m.Account == login.Account && m.Password == login.Password).FirstOrDefaultAsync();


            if (result == null)
            {
                //4.2.6 將ViewData["Error"]加入Login View
                ViewData["Error"] = "帳號或密碼錯誤!!";
                return View();
            }
            else
            {
                //Session["Manager"] = "已登入";

                HttpContext.Session.SetString("Manager", JsonConvert.SerializeObject(login));

                return RedirectToAction("Index", "Books");
            }



        }

        public IActionResult Logout()
        {


            HttpContext.Session.Remove("Manager");
            return RedirectToAction("Index", "Home");

            //return View();
        }
    }
}

Controllers/PostBooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;

namespace MyModel_CodeFirst.Controllers
{
    public class PostBooksController : Controller
    {
        private readonly GuestBookContext _context;

        public PostBooksController(GuestBookContext context)
        {
            _context = context;
        }

        //3.1.6 修改Index Action的寫法
        public async Task<IActionResult> Index()
        {
            //var book = await _context.Book.ToListAsync();

            var book = _context.Book.OrderByDescending(b => b.TimeStamp).ThenByDescending(b => b.GId);

            return View(await book.ToListAsync());

            //return View(await _context.Book.ToListAsync());
        }

        // GET: PostBooks/Details/5
        public async Task<IActionResult> Display(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.GId == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: PostBooks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PostBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book book, IFormFile? uploadPhoto)
        {
            //上傳照片的處理

            if (uploadPhoto != null)
            {
                if (uploadPhoto.ContentType != "image/jpeg" && uploadPhoto.ContentType != "image/png")
                {
                    ViewData["Message"] = "請上傳jpg或png格式的檔案!!";
                    return View(book);
                }

                //把檔案轉成二進位資料,並放入byte[]
                using (var mem = new MemoryStream())
                {
                    uploadPhoto.CopyTo(mem);

                    book.Photo = mem.ToArray();
                    book.ImageType = uploadPhoto.ContentType;
                }
            }

            book.TimeStamp = DateTime.Now;


            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        //3.1.5 修改PostBooksController，移除Edit、Delete Action

        private bool BookExists(long id)
        {
            return _context.Book.Any(e => e.GId == id);
        }


        public IActionResult ExceptionTest()
        {
            int a = 0;
            int s;

            if (a == 0)
            {
                // 當 a 為 0 時，返回一個包含連結的 HTML 內容
                string url = "https://traffic.tbkc.gov.tw/";
                string htmlContent = $"<a href='{url}' target='_blank'>Click here to visit the traffic website</a>";
                return Content(htmlContent, "text/html");
            }
            else
            {
                // 正常情況下處理除法
                s = 100 / a;
            }

            // 可以根據需要返回其他內容或視圖
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
@{
    //如果沒有登入過的話,我就導回首頁
    //  bool manager = false;

    var Manager = Context.Session.GetString("Manager");

    if (Manager == null)
    {
        Context.Response.Redirect("/Home/Index");
    }
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | F H 找到了</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyModel_CodeFirst.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Total</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       不塞車 

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">路況</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Books" asp-action="Index">旅點</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="#" asp-action="Index">法規</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="#" asp-action="Index">各路</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="#" asp-action="Index">任務</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="#" asp-action="Index">系統</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">免責</a>
                        </li>
                    </ul>
                    <div>
                        <a asp-action="Logout" asp-controller="Login" class="btn btn-light">登出</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Copyright &copy; @DateTime.Now.Year - 我不識很重要 - <a asp-area="" asp-controller="Home" asp-action="Privacy">本站隱私權政策</a> | 最後更新時間: @DateTime.Now
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)  @*這是動態載入JS的程式*@
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | 速通路指</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyModel_CodeFirst.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">F H</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">路況</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="PostBooks" asp-action="Index">資訊中心</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="PostBooks" asp-action="ExceptionTest">K交通動態網</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">免責宣言</a>
                        </li>
                    </ul>
                    <div>
                        <a asp-action="Login" asp-controller="Login" class="btn btn-outline-light">登入</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container text-center"  >
             Copyright &copy; @DateTime.Now.Year - 速通 - <a asp-area="" asp-controller="Home" asp-action="Privacy">本站隱私權政策</a> | 最後更新時間: @DateTime.Now
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)  @*這是動態載入JS的程式*@
</body>
</html>